name: Test Split String

on: [push]

jobs:
  split-string-into-array:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Split String
        run: |
          pwd
          ls -a
          base_package="com.modyo.package"
          echo $base_package
          read -r -a package_folders <<< $base_package
          echo "package_folders: $package_folders"
          package_folders=${base_package//.//}
          echo "package_folders: $package_folders"
          base_folder="$(pwd)/src/main/java"
          echo "base_folder: $base_folder"
          cd $base_folder
          mkdir -p $package_folders
          source_path="$base_folder/com/modyo/example/"
          destination_path="$base_folder/com/modyo/package/"
          echo "mv $source_path* $destination_path"
          mv $source_path* $destination_path
          cd $source_path
          pwd
          ls -a
          cd $destination_path
          pwd
          ls -a

#          cd $package_folders
#          mv * $package_folders
#          mv com/modyo/example/* $package_folder
#          cd com/modyo/example
