name: Test Split String

on: [push]

jobs:
  split-string-into-array:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Split String
        run: |
          pwd
          ls -a
          new_package="com.modyo.package"
          echo $new_package
          package_folders=${new_package//.//}
          echo "package_folders: $package_folders"
          base_folder="$(pwd)/src/main/java"
          echo "cd $base_folder"
          cd $base_folder
          pwd
          ls -a
          echo "crear $package_folders"
          mkdir -p $package_folders
          pwd
          ls -a
          echo "crear temp"
          mkdir -p temp
          pwd
          ls -a
          echo "source_path: $base_folder/com/modyo/example/"
          source_path="$base_folder/com/modyo/example/"
          echo "temp_path: $base_folder/temporary/"
          temp_path="$base_folder/temporary/"
          echo "destination_path: $base_folder/$package_folder"
          destination_path="$base_folder/$package_folder"          
          echo "mover $source_path* $temp_path"
          mv $source_path* $temp_path
#          cd $package_folders
#          mv * $package_folders
#          mv com/modyo/example/* $package_folder
#          cd com/modyo/example
#          read -r -a package_folders <<< $new_package
#          echo "package_folders: $package_folders"
#          ${temp_path%%/*}

