name: Test Split String

on: [push]

jobs:
  split-string-into-array:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Split String
        run: |
          pwd
          ls -a
          base_package="com.modyo.package"
          echo $base_package
          read -r -a package_folders <<< $base_package
          echo "package_folders: $package_folders"
          package_folders=${base_package//.//}
          echo "package_folders: $package_folders"
          cd src/main/java
          mkdir -p $package_folders
          cd com/modyo/example/domain
          pwd
          ls -a
          cd ..
          cd ..
          cd ..
          cd ..
          mv -r com/modyo/example/* $package_folder
          cd $package_folders
          pwd
          ls -a
#          cd $package_folders
#          mv * $package_folders
